[versions]
android-minSdk = "21"
android-compileSdk = "34"
release-version = "0.4.0"
release-versionCode = "5"

agp = "8.6.1"

kotlin = "1.9.22"

junit = "4.13.2"

androidx-appcompat = "1.6.1"
androidx-benchmark = "1.2.2"
androidx-constraintlayout = "2.1.4"
androidx-core-ktx = "1.12.0"
androidx-lifecycle = "2.6.2"
androidx-test-espresso = "3.5.1"
androidx-test-ext = "1.1.5"
androidx-test-runner = "1.5.2"

google-material = "1.11.0"

photoview = "2.3.0"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-benchmark-junit = { module = "androidx.benchmark:benchmark-junit4", version.ref = "androidx-benchmark" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-test-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }

google-material = { module = "com.google.android.material:material", version.ref = "google-material" }

photoview = { module = "com.github.Baseflow:PhotoView", version.ref = "photoview" }

junit = { module = "junit:junit", version.ref = "junit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
androidx-benchmark = { id = "androidx.benchmark", version.ref = "androidx-benchmark" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
